kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80   # Porta para o Ingress Controller
        hostPort: 80
      - containerPort: 443  # Porta para o Ingress Controller (HTTPS)
        hostPort: 443
  - role: worker
  - role: worker

# Optional feature gates, API Server, etc.
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
